// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// draw_allele
int draw_allele(int x);
RcppExport SEXP _simfam_draw_allele(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_allele(x));
    return rcpp_result_gen;
END_RCPP
}
// geno_fam_cpp
IntegerMatrix geno_fam_cpp(IntegerMatrix X_in, IntegerVector i_founder_in, IntegerVector i_founder_out, IntegerVector i_child, IntegerVector i_pat, IntegerVector i_mat);
RcppExport SEXP _simfam_geno_fam_cpp(SEXP X_inSEXP, SEXP i_founder_inSEXP, SEXP i_founder_outSEXP, SEXP i_childSEXP, SEXP i_patSEXP, SEXP i_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_founder_in(i_founder_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_founder_out(i_founder_outSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_child(i_childSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_pat(i_patSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_mat(i_matSEXP);
    rcpp_result_gen = Rcpp::wrap(geno_fam_cpp(X_in, i_founder_in, i_founder_out, i_child, i_pat, i_mat));
    return rcpp_result_gen;
END_RCPP
}
// indexes_chr
IntegerVector indexes_chr(IntegerVector chrs);
RcppExport SEXP _simfam_indexes_chr(SEXP chrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type chrs(chrsSEXP);
    rcpp_result_gen = Rcpp::wrap(indexes_chr(chrs));
    return rcpp_result_gen;
END_RCPP
}
// indexes_chr_pos
IntegerVector indexes_chr_pos(IntegerVector pos, int chr_start, int chr_end, int pos_start, int pos_end);
RcppExport SEXP _simfam_indexes_chr_pos(SEXP posSEXP, SEXP chr_startSEXP, SEXP chr_endSEXP, SEXP pos_startSEXP, SEXP pos_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< int >::type chr_start(chr_startSEXP);
    Rcpp::traits::input_parameter< int >::type chr_end(chr_endSEXP);
    Rcpp::traits::input_parameter< int >::type pos_start(pos_startSEXP);
    Rcpp::traits::input_parameter< int >::type pos_end(pos_endSEXP);
    rcpp_result_gen = Rcpp::wrap(indexes_chr_pos(pos, chr_start, chr_end, pos_start, pos_end));
    return rcpp_result_gen;
END_RCPP
}
// kinship_fam_sparse_cpp
S4 kinship_fam_sparse_cpp(S4 kinship, IntegerVector pars1_R, IntegerVector pars2_R, CharacterVector ids_new_R);
RcppExport SEXP _simfam_kinship_fam_sparse_cpp(SEXP kinshipSEXP, SEXP pars1_RSEXP, SEXP pars2_RSEXP, SEXP ids_new_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type kinship(kinshipSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pars1_R(pars1_RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pars2_R(pars2_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids_new_R(ids_new_RSEXP);
    rcpp_result_gen = Rcpp::wrap(kinship_fam_sparse_cpp(kinship, pars1_R, pars2_R, ids_new_R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simfam_draw_allele", (DL_FUNC) &_simfam_draw_allele, 1},
    {"_simfam_geno_fam_cpp", (DL_FUNC) &_simfam_geno_fam_cpp, 6},
    {"_simfam_indexes_chr", (DL_FUNC) &_simfam_indexes_chr, 1},
    {"_simfam_indexes_chr_pos", (DL_FUNC) &_simfam_indexes_chr_pos, 5},
    {"_simfam_kinship_fam_sparse_cpp", (DL_FUNC) &_simfam_kinship_fam_sparse_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_simfam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
