# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_allele <- function(x) {
    .Call(`_simfam_draw_allele`, x)
}

geno_fam_cpp <- function(X_in, i_founder_in, i_founder_out, i_child, i_pat, i_mat) {
    .Call(`_simfam_geno_fam_cpp`, X_in, i_founder_in, i_founder_out, i_child, i_pat, i_mat)
}

